# Generated by Django 4.1.1 on 2023-02-04 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Patent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patentapplication',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
