# Generated by Django 4.1.1 on 2023-02-04 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
